<Project>
  <PropertyGroup>
    <Version Condition="'$(Version)' == ''">0.1.0</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(Version).0</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(Version).0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
